import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("data/restaurants.csv", encoding='latin-1')
print("Dataset Loaded Successfully\n")
print("\n--- TOP CUISINES ---")
cuisines = df['Cuisines'].dropna().str.split(', ')
all_cuisines = cuisines.explode()
top_cuisines = all_cuisines.value_counts().head(3)
print("Top 3 Cuisines:")
print(top_cuisines)
percentage = (top_cuisines / len(df)) * 100
print("\nPercentage of Restaurants Serving Them:")
print(percentage)
print("\n--- CITY ANALYSIS ---")
city_counts = df['City'].value_counts()
print("City with highest restaurants:")
print(city_counts.head(1))
city_ratings = df.groupby('City')['Aggregate rating'].mean()
print("\nAverage Rating per City:")
print(city_ratings.head())
print("\nCity with highest average rating:")
print(city_ratings.sort_values(ascending=False).head(1))
print("\n--- PRICE RANGE DISTRIBUTION ---")
plt.figure(figsize=(8,5))
sns.countplot(x='Price range', data=df)
plt.title("Distribution of Price Range")
plt.xlabel("Price Range")
plt.ylabel("Number of Restaurants")
plt.show()
price_percentage = df['Price range'].value_counts(normalize=True)*100
print("\nPercentage of Restaurants in Each Price Range:")
print(price_percentage)
print("\n--- ONLINE DELIVERY ANALYSIS ---")
online_delivery = df['Has Online delivery'].value_counts(normalize=True)*100
print("Percentage offering Online Delivery:")
print(online_delivery)
delivery_rating = df.groupby('Has Online delivery')['Aggregate rating'].mean()
print("\nAverage Rating Comparison:")
print(delivery_rating)
print("\n--- RATING DISTRIBUTION ---")
plt.figure(figsize=(8,5))
sns.histplot(df['Aggregate rating'], bins=10)
plt.title("Distribution of Restaurant Ratings")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.show()
avg_votes = df['Votes'].mean()
print("\nAverage Votes Received by Restaurants:")
print(avg_votes)
print("\nAnalysis Completed Successfully!")

